### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by connorryanbaker** [jdelrom/fullstackOT#1]
Hey JD,
Design Docs are looking good so far! Just a few notes moving forward.

- [x] Time Line for each MVP. Allotting a number of days for each feature will help you focus your efforts; the ten days will go by quickly and it is best to have an idea of how your time will be spent.

- [x] At the moment, your git repo is nested; remove the git repo from the outer folder on your machine and reinitialize it in the Rails project directory. Let me know if you need any help with this step.

- [x] Your schema is looking good! The one obvious note would be that tables for Ratings and Reviews are missing. These should be relatively straightforward to implement.

Let me know if you have any questions!

**Comment by jdelrom** [comment]
Hey Connor, i can't seem to unnest my repo.  Well I did, but when I try and push my local stuff up to git hub i get these errors:

JDs-Mac:opentableFS jdelrom$ git push -u origin master
To https://github.com/jdelrom/fullstackOT.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/jdelrom/fullstackOT.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
JDs-Mac:opentableFS jdelrom$
